spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecc
    password: ecc
    username: ecc
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
jwt:
  secret: fBvgt1jt+NIK5xPADxAbMp7C4k5fkSXZMg0lZX8yV4KcSRxqWDS1gglJW575pzcc
  lifetime: 30m